# Generated by Django 4.1.1 on 2022-09-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
