# Generated by Django 4.1.1 on 2022-09-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_remove_client_license_own_license_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='client',
            new_name='client_name',
        ),
    ]
