# Generated by Django 4.1.1 on 2022-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_rename_client_license_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='client_name',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
